"""Ajustes para Issue 8 (Notificaciones)

Revision ID: 4b156db9ad98
Revises: f38af05681e0
Create Date: 2025-11-11 02:10:58.922779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b156db9ad98'
down_revision: Union[str, Sequence[str], None] = 'f38af05681e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
