"""Ajustes modelos Conversacion y Mensaje Issue 7

Revision ID: 52e2ae8cffc3
Revises: 9ed0a599b4d6
Create Date: 2025-11-10 22:31:10.902886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e2ae8cffc3'
down_revision: Union[str, Sequence[str], None] = '9ed0a599b4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
