"""Migracion inicial SQLite

Revision ID: 7fac33b71a0c
Revises: 
Create Date: 2025-11-14 23:19:39.996658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fac33b71a0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_producto', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('fecha_agregado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('fecha_ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('estado_cuenta', sa.String(length=20), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_table('carrito',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('fecha_mensaje', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('email_contacto', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('direccion_envio', sa.Text(), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('conversaciones',
    sa.Column('id_conversacion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario_remitente', sa.Integer(), nullable=False),
    sa.Column('id_usuario_destinatario', sa.Integer(), nullable=False),
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('tipo_participacion', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_mensaje'], ['mensajes.id_mensaje'], ),
    sa.ForeignKeyConstraint(['id_usuario_destinatario'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_usuario_remitente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_conversacion')
    )
    op.create_table('items_carrito',
    sa.Column('id_item_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_carrito', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrito'], ['carrito.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item_carrito'),
    sa.UniqueConstraint('id_carrito', 'id_producto', name='_carrito_producto_uc')
    )
    op.create_table('itemspedido',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemspedido')
    op.drop_table('items_carrito')
    op.drop_table('conversaciones')
    op.drop_table('pedidos')
    op.drop_table('mensajes')
    op.drop_table('carrito')
    op.drop_table('usuario')
    op.drop_table('productos')
    # ### end Alembic commands ###
