"""Ajuste de modelos de Pedido

Revision ID: 86b5d7206ba6
Revises: ef7bf13150d2
Create Date: 2025-11-09 18:30:39.501134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b5d7206ba6'
down_revision: Union[str, Sequence[str], None] = 'ef7bf13150d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
