"""Ajustes modelos Conversacion y Mensaje Issue 7

Revision ID: 9ed0a599b4d6
Revises: 86b5d7206ba6
Create Date: 2025-11-10 22:17:25.745834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed0a599b4d6'
down_revision: Union[str, Sequence[str], None] = '86b5d7206ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
